version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: feedbackcampus-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: feedbackcampus
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: